---
title: "Exploration"
author: "Colin Busby"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(parallel)
library(rpart)
library(readr)
library(tidyverse)
library(janitor)
library(ggplot2)
library(car)
library(MASS)
library(dplyr)
library(Hmisc)
library(forcats)
```


```{r}
players <- read_csv("players.csv")
active_p <- read_csv("active_players_2.csv")
```

```{r}
str(active_p)
```

## Remove `NaN` from `Salary`

```{r}
hist(active_p$Salary)
```

```{r}
sum(is.na(active_p))
#percent missing values per variable
apply(active_p, 2, function(col)sum(is.na(col))/length(col))
```

```{r}
#identifying the rows with NAs
rownames(active_p)[apply(active_p, 2, anyNA)]
#removing all observations with NAs
ap_clean <- active_p %>% na.omit()
```

### Factors

```{r}
# Transforming Team,Position,College into factors
ap_clean_f <- transform (
  ap_clean,
  fTeam = as.factor(Team),
  fPosition = as.factor(Position),
  fCollege = as.factor(College)
)
```

```{r}
str(ap_clean_f)
```

```{r}
colSums(is.na(ap_clean_f))
```

## Setting `NA` as a factor level for `fCollege` - Not Necessary, `nan` is NA in ap_clean_f

https://stackoverflow.com/questions/27195956/convert-na-into-a-factor-level

```{r}
#rm(ap_clean_college)
```

```{r}
#identifying the rows with NAs
#rownames(active_p)[apply(active_p, 2, anyNA)]
#removing all observations with NAs
#ap_clean_college <- active_p %>% na.omit()
ap_clean_college <- active_p[!(is.na(active_p$Salary)), ]
```

```{r}
# Transforming Team,Position,College into factors
ap_cc_f <- transform (
  ap_clean_college,
  fTeam = as.factor(Team),
  fPosition = as.factor(Position),
  fCollege = as.factor(College)
)
```

```{r}
str(ap_cc_f)
```

```{r}
colSums(is.na(ap_cc_f))
```

## Adding Rebounds, Points and Assists from `players.csv` to `ap_clean_f`

### Clean `players.csv`

```{r}
sum(is.na(players))
#percent missing values per variable
apply(players, 2, function(col)sum(is.na(col))/length(col))
rm(players_clean)
```

```{r}
#identifying the rows with NAs
rownames(players)[apply(players, 2, anyNA)]
#removing all observations with NAs
players_clean <- players %>% drop_na(Salary)
```

```{r}
players_clean
```
```{r}
# Transforming Team,Position,College into factors
pl_clean_f <- transform (
  players_clean,
  fTeam = as.factor(Team),
  fPosition = as.factor(Position),
  fCollege = as.factor(College)
)
```

```{r}
# bind_cols(ap_clean_f, players_clean['Points'])
# bind_cols(ap_clean_f, players_clean['Rebounds'])
# bind_cols(ap_clean_f, players_clean['Assists'])
```


